name: Minify Plugin
permissions:
  contents: write
  pages: write 
on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Auto Minify
      uses: nizarmah/auto-minify@v2.1
      
    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
